### ISSUE TITLE
 How I get the *ssh.Client?  Thanks very much~

### ISSUE THREAD

**Issue by yxxhero** [helloyi/go-sshclient#10]
https://github.com/helloyi/go-sshclient/blob/5bb6d0ba19940376461ce8c131effef51e57a451/sshclient.go#L29-L31

How I get the *ssh.Client?  Thanks very much~

**Comment by helloyi** [comment]
Why do you get the underlying ssh.Client?
It's good to start from the problem.

**Comment by yxxhero** [comment]
when I use github.com/bramvdbogaerde/go-scp, It require the ssh.Client. In many opensource project, it base on the native ssh.Client.  are you chinese people? My english is not very good. @helloyi

**Comment by helloyi** [comment]
I see. Let's go here https://github.com/helloyi/go-sshclient/pull/11

**Comment by mr-tron** [comment]
please add new git tag with new version on latest commit

**Comment by helloyi** [comment]
done!
