### ISSUE TITLE
How to upload files

### ISSUE THREAD

**Issue by SharkFourSix** [helloyi/go-sshclient#16]
How do you upload files through a connection?

**Comment by helloyi** [comment]
A good idea is to use [sftp](github.com/pkg/sftp).

If you want to use with [go-sshclient](https://github.com/helloyi/go-sshclient), You  should use `sshclient.UnderlyingClient()` to get the `ssh.Client`, And new sftp client, like this `sftpCli, err := sftp.NewClient(sshclient.UnderlyingClient())`.

If you want to learn how to transfer files over ssh, maybe you should read the [sftp](github.com/pkg/sftp) source.

Hope this helps.
