### ISSUE TITLE
It is impossible to get v2.0.0 version

### ISSUE THREAD

**Issue by jthann** [helloyi/go-sshclient#19]
When using ```go get -u github.com/helloyi/go-sshclient```, it always return v1.1.1 version， According to semantic version spec if major version greater than v1, it should append to go module name，So module github.com/helloyi/go-sshclient should change to module github.com/helloyi/go-sshclient/v2 in v2.x.

**Comment by helloyi** [comment]
Thank you for the reminder. 
The latest version number should be v1.2.0, according to the [semver](https://semver.org/) specification. 
Do the necessary processing if you are using the latest version.
