### ISSUE TITLE
Support for diffie-hellman-group1-sha1 and Ciphers aes128-cbc and others

### ISSUE THREAD

**Issue by felipelyp** [helloyi/go-sshclient#23]
I'm trying to connect to an ssh server with an insecure connection, I can even configure some things but it always gives me an error [no password].

_No SSH Config_

![image](https://github.com/helloyi/go-sshclient/assets/28626603/434ecd79-892e-4aae-bc82-9c192f006726)

Error: 

**2024/01/03 08:54:21 ssh: handshake failed: ssh: no common algorithm for key exch
ange; client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-
nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 dif
fie-hellman-group14-sha1 ext-info-c kex-strict-c-v00@openssh.com], server offere
d: [diffie-hellman-group1-sha1]**

_With SSH Config_

![image](https://github.com/helloyi/go-sshclient/assets/28626603/ecfbe23f-d8ab-4f50-a0fa-27ad47a69fc6)

Error: 

**2024/01/03 08:52:58 ssh: handshake failed: ssh: unable to authenticate, attempte
d methods [none password], no supported methods remain**

**Comment by helloyi** [comment]
This issue has been resolved. Please see https://stackoverflow.com/questions/58459755/error-while-trying-to-connect-via-ssh-to-remote-host
