### ISSUE TITLE
Typo in TerminalConfig struct

### ISSUE THREAD

**Issue by rnsc** [helloyi/go-sshclient#6]
There's a typo in the following code, it should be "Height" instead of "Hight"

```
type TerminalConfig struct {
	Term   string
	Hight  int
	Weight int
	Modes  ssh.TerminalModes
}
```

**Comment by helloyi** [comment]
Thank you for the correction, the issue has been fixed.

https://github.com/helloyi/go-sshclient/compare/7e5120a78b77a2970e20f3e8ca42ac4e7d03d3d6...f1e2055010055be75ab3671416616859f18937ee
