### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by mr-pmillz** [helloyi/go-sshclient#9]
It would be nice if this project supported proxy servers.
For example, if you're connecting through a bastion or a jump box, to have that as an option.
Something like,
```go
sshclient.DialWithProxy("host:port", "username", "pkey", "proxyhost:port", "proxy-username", "proxy-pkey")
```
or something like that.

**Comment by helloyi** [comment]
This is a very practical requirement, and there are some simple ways to do it:
+ Use ssh tunnel + go-sshclient library to implement it.
+ Deploy a specific (any method is fine)  sshclient (based on go-sshclient) on the channel machine, and connect to the tunnel machine, then execute the command(sshclient) to connect to the target host.

Support directly in go-sshclient, not elegant.

Do you have any advice?
